var testapicList = [
	{ title: 'check mark', character: '✔' },
	{ title: 'cross mark', character: '❌' },
	{ title: 'warning', character: '⚠' },
	{ title: 'backhand index pointing right', character: '👉' },
	{ title: 'right arrow', character: '➡' },
	{ title: 'down arrow', character: '⬇' },
	{ title: 'light bulb', character: '💡' },
	{ title: 'locked', character: '🔒' },
	{ title: 'bell', character: '🔔' },
	{ title: 'collision', character: '💥' },
	{ title: 'police car light', character: '🚨' },
	{ title: 'hammer and wrench', character: '🛠' },
	{ title: 'round pushpin', character: '📍' },
	{ title: 'laptop', character: '💻' },
	{ title: 'mobile phone', character: '📱' },
	{ title: 'speech balloon', character: '💬' },
	{ title: 'movie camera', character: '🎥' },
	{ title: 'bar chart', character: '📊' },
	{ title: 'speaking head', character: '🗣' },
	{ title: 'bust in silhouette', character: '👤' },
	{ title: 'busts in silhouette', character: '👥' },
	{ title: 'magnifying glass tilted right', character: '🔎' },
	{ title: 'sun', character: '☀' },
	{ title: 'sun behind cloud', character: '⛅' },
	{ title: 'cloud with rain', character: '🌧' },
	{ title: 'flag: France', character: '🇫🇷' },
	{ title: 'flag: United States', character: '🇺🇸' },
	{ title: 'flag: United Kingdom', character: '🇬🇧' },
	{ title: 'flag: Australia', character: '🇦🇺' },
]

export default testapicList;